### ISSUE TITLE
Tensor3D Colum Major Ordering

### ISSUE THREAD

**Issue by bariskurt** [bariskurt/pml#2]
I've just changed the index calculation of the Tensor3D from 
**data_[i0*size1_*size2_ + i2*size1_ + i1];**
to
**data_[i0 + size0_ * (i1 + size1_ * i2)]**
which is the correct way of column major ordering as you can find here:

http://www.obliquity.com/computer/fortran/array.html
https://en.wikipedia.org/wiki/Row-major_order

This probably broke some parts of the Tensor3D. @cagatayyildiz  should have a look at this.

**Comment by cagatayyildiz** [comment]
I fixed the issue. Now, data in Tensor3D are stored in column-major and slice extractors are updated accordingly. A Tensor3D object is now indexed from the end (Matlab style, not Python).
